### ISSUE TITLE
UI FXComponent doesn't recognize the controls in fxml file, imported using fx:include

### ISSUE THREAD

**Issue by suyambuganesh** [JacpFX/JacpFX#24]
Hi Andy,

FXComponent view doesn't initialize the controls in the fxml file which are included using tag <fx:include>. In the below example, the control with id apperror is null in the instantiated FXComponent

for example,

contents of main.fxml
```
<BorderPane prefHeight="211.0" prefWidth="225.0" xmlns="http://javafx.com/javafx/8" xmlns:fx="http://javafx.com/fxml/1">
    <center>
        
    </center>
   <bottom>
        <fx:include source="footer.fxml" />
    </bottom>
</BorderPane>
```
contents of footer.xml
```
<HBox alignment="CENTER_RIGHT" maxHeight="-Infinity" >
    <children>
      <Button fx:id="apperror" mnemonicParsing="false" text="" style="-fx-background-color: white;"/>
     </children>
    <padding>
        <Insets bottom="12.0" left="12.0" right="12.0" top="12.0" />
    </padding>
</HBox>
```

**Comment by amoAHCP** [comment]
Hi, 
currently the FXComponent / FXML binding is only for the root FXML. I assume that you want to bind the "HBox" and the "BorderPane" FXML to the same FXComponent. This is currently not supported by JacpFX directly (I must check if I can provide this because this can be an unwanted behavior to set the FXComponent to all chlid files)... a valid way to do is this one: https://github.com/sialcasa/jfx-nested-controllers-example/tree/master/src/de/saxsys/fxml ... you apply an separate controller to the child, which can be injected to the FXComponent.
