### ISSUE TITLE
Not all Nodes can be used as targets

### ISSUE THREAD

**Issue by mamayoleksandr** [JacpFX/JacpFX#29]
Hi Andy,

For example, if I use ScrollPane as target in perspective component's ui is ignored and not injected into the target. So far GridPane is working fine for me as target.

thanks,

Alex.

**Comment by JacpFX** [comment]
Hi Alex, 
I had alteady used ScrollPanes as target?! Have you tried the ScienecView to analyze the Scene structure? Maybe it is a resizing issue? I will check it on monday when I am back...

Andy

**Comment by amoAHCP** [comment]
Hi Alex,
you are right ScrollPane uses "setContent". I find it a bit annoying that some Nodes works different, set a content pane to your ScrollPane and register this Pane as target. There is no general solution for this, because I want to avoid "automatic wrapping" because you loose control over your UI.
